require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  # DisabledByDefault: true
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/schema.rb"
    - "config/puma.rb"
    - "config/initializers/backtrace_silencers.rb"
    - "config/initializers/content_security_policy.rb"
    - "config/environments/production.rb"
    - "config/initializers/devise.rb"
    - "db/migrate/20231124001419_create_active_storage_tables.active_storage.rb"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/HashTransformValues:
  Exclude:
    - "test/support/pretty_diff.rb"

Metrics/BlockLength:
  AllowedMethods: ["context"]
  Exclude:
    - "config/environments/development.rb"
    - "config/routes.rb"
    - "config/environments/devise.rb"
    - "test/controllers/**/*"

Naming/MethodParameterName:
  Exclude:
    - "app/models/logics/lo/pages.rb"
    - "app/resources/los/view_lo_resource.rb"