version: "3.8"
services:
  api:
    restart: always
    image: ghcr.io/marczaltsigp/farma_api
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
        " # Removing server.pid is technically a cleanup script
    ports:
      - 3001:3000
    env_file: .env    
    volumes:
      - ./storage:/app/storage
      - ./log:/app/log
      - /dev/shm:/dev/shm
    tmpfs:
      - /tmp
    depends_on:
      - db
    networks:
      - farma-network
        
  db:
    image: postgres
    env_file: .env  
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - farma-network

volumes:
  pgdata:
    driver: local
  bundle_path:

networks:
  farma-network:
    driver: bridge
